"""Agent registration + health (guide §7.7, plan 05 §4 agent v1).

POST /agents returns the raw ingestion token EXACTLY ONCE plus a pre-filled
docker-compose.agent.yml — only the sha256 hash is stored (guide §5.2). The
agent then authenticates /ingest and /agents/heartbeat with that bearer token
(routes in api.ingestion).
"""

from __future__ import annotations

import hashlib
import secrets
import uuid

from fastapi import APIRouter, HTTPException
from sqlalchemy import select

from api.deps import DbDep, PrincipalDep, SettingsDep
from api.schemas import AgentOut, AgentRegisterIn, AgentRegisterOut
from shared.db.models import Agent, Connector

router = APIRouter(tags=["agents"])

COMPOSE_TEMPLATE = """\
# docker-compose.agent.yml — generated by Forecast Platform agent onboarding.
# Run this OUTSIDE the main stack, on the machine that can reach your source
# API. Your source credential goes in SOURCE_API_KEY below and never leaves
# this machine (guide §7) — the agent only ever sends numeric points.
services:
  forecast-agent:
    build: ./agent            # or the published signed image once releases exist
    restart: unless-stopped
    environment:
      FORECAST_API_URL: {api_url}
      FORECAST_AGENT_TOKEN: "{token}"
      # The env var name(s) referenced by secret_env in agent.config.yaml:
      SOURCE_API_KEY: "put-your-source-api-key-here"
    volumes:
      - ./agent.config.yaml:/app/agent.config.yaml:ro
"""


def _to_out(agent: Agent) -> AgentOut:
    return AgentOut(
        id=agent.id,
        connector_id=agent.connector_id,
        status=agent.status,
        last_heartbeat_at=agent.last_heartbeat_at,
        created_at=agent.created_at,
    )


@router.post("/agents", response_model=AgentRegisterOut, status_code=201)
def register_agent(
    body: AgentRegisterIn, db: DbDep, principal: PrincipalDep, settings: SettingsDep
) -> AgentRegisterOut:
    connector = db.scalar(
        select(Connector).where(
            Connector.id == body.connector_id,
            Connector.organization_id == uuid.UUID(principal.org_id),
        )
    )
    if connector is None:
        raise HTTPException(404, "connector not found")

    raw_token = secrets.token_urlsafe(32)
    agent = Agent(
        organization_id=uuid.UUID(principal.org_id),
        connector_id=connector.id,
        ingestion_token_hash=hashlib.sha256(raw_token.encode("utf-8")).hexdigest(),
    )
    db.add(agent)
    db.flush()

    compose = COMPOSE_TEMPLATE.format(api_url=settings.api_url, token=raw_token)
    return AgentRegisterOut(agent=_to_out(agent), ingestion_token=raw_token, compose_file=compose)


@router.get("/agents", response_model=list[AgentOut])
def list_agents(db: DbDep, principal: PrincipalDep) -> list[AgentOut]:
    rows = db.scalars(
        select(Agent)
        .where(Agent.organization_id == uuid.UUID(principal.org_id))
        .order_by(Agent.created_at)
    ).all()
    return [_to_out(a) for a in rows]


@router.post("/agents/{agent_id}/revoke", response_model=AgentOut)
def revoke_agent(agent_id: uuid.UUID, db: DbDep, principal: PrincipalDep) -> AgentOut:
    from datetime import UTC, datetime

    agent = db.scalar(
        select(Agent).where(
            Agent.id == agent_id, Agent.organization_id == uuid.UUID(principal.org_id)
        )
    )
    if agent is None:
        raise HTTPException(404, "agent not found")
    agent.status = "revoked"
    agent.revoked_at = datetime.now(tz=UTC)
    return _to_out(agent)
