/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connector-definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Definitions */
        get: operations["list_definitions_connector_definitions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Connectors */
        get: operations["list_connectors_connectors_get"];
        put?: never;
        /** Create Connector */
        post: operations["create_connector_connectors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/{connector_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Connector */
        get: operations["get_connector_connectors__connector_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Connector
         * @description Delete a connector and everything under it (metrics/points cascade).
         *     The stored secret is revoked first so no orphaned credential lingers in
         *     the SecretsProvider (guide §7.5 instant-revocation posture).
         */
        delete: operations["delete_connector_connectors__connector_id__delete"];
        options?: never;
        head?: never;
        /** Update Connector */
        patch: operations["update_connector_connectors__connector_id__patch"];
        trace?: never;
    };
    "/connectors/{connector_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Connector Runs
         * @description Poll audit history for the connector detail screen (doc 1 §7).
         */
        get: operations["list_connector_runs_connectors__connector_id__runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/{connector_id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Metrics */
        get: operations["list_metrics_connectors__connector_id__metrics_get"];
        put?: never;
        /** Create Metric */
        post: operations["create_metric_connectors__connector_id__metrics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List All Metrics
         * @description Org-wide dataset list with sparklines (doc 4 §3).
         */
        get: operations["list_all_metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/{metric_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Metric */
        get: operations["get_metric_metrics__metric_id__get"];
        put?: never;
        post?: never;
        /** Delete Metric */
        delete: operations["delete_metric_metrics__metric_id__delete"];
        options?: never;
        head?: never;
        /** Update Metric */
        patch: operations["update_metric_metrics__metric_id__patch"];
        trace?: never;
    };
    "/metrics/{metric_id}/forecasts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Metric Forecasts
         * @description Forecast history, newest first — lets the UI reload the latest result.
         */
        get: operations["list_metric_forecasts_metrics__metric_id__forecasts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/{metric_id}/anomalies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Metric Anomalies */
        get: operations["list_metric_anomalies_metrics__metric_id__anomalies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/{metric_id}/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Metric Data */
        get: operations["get_metric_data_metrics__metric_id__data_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/{metric_id}/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enqueue Forecast
         * @description Insert a pending forecast_runs row — the row IS the job (doc 1 §5.4).
         *     `worker` polls pending rows, calls `ml`, and writes the result back.
         */
        post: operations["enqueue_forecast_metrics__metric_id__forecast_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forecasts/{forecast_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Forecast */
        get: operations["get_forecast_forecasts__forecast_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forecasts/{forecast_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Forecast
         * @description Stream the export AND record an export_jobs row + stored artifact so a
         *     share link exists for every export (guide §6.2).
         */
        get: operations["export_forecast_forecasts__forecast_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forecasts/{forecast_id}/share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Share Forecast
         * @description Create a shareable expiring link (export_jobs.share_token, guide §6.2).
         */
        post: operations["share_forecast_forecasts__forecast_id__share_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exports/{share_token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Shared Export
         * @description Public share-link download — the token IS the capability locally
         *     (doc 1 §6.5); expiry enforced against export_jobs.expires_at.
         */
        get: operations["download_shared_export_exports__share_token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/{webhook_token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Webhook Ingress */
        post: operations["webhook_ingress_webhooks__webhook_token__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Agent Ingest */
        post: operations["agent_ingest_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Agent Heartbeat */
        post: operations["agent_heartbeat_agents_heartbeat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agents */
        get: operations["list_agents_agents_get"];
        put?: never;
        /** Register Agent */
        post: operations["register_agent_agents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agent_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke Agent */
        post: operations["revoke_agent_agents__agent_id__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/{metric_id}/eda": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Eda */
        get: operations["latest_eda_metrics__metric_id__eda_get"];
        put?: never;
        /** Generate Eda */
        post: operations["generate_eda_metrics__metric_id__eda_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notifications */
        get: operations["list_notifications_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Read */
        post: operations["mark_read_notifications__notification_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark All Read */
        post: operations["mark_all_read_notifications_read_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/unread-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Unread Count
         * @description A single COUNT(*) for the header bell — polled every 30s, so it must stay
         *     cheap. Avoids the full /dashboard payload (8 aggregates, incl. an unbounded
         *     DataPoint count) when all the bell needs is the unread total.
         */
        get: operations["unread_count_notifications_unread_count_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/sample-metric": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sample Metric */
        get: operations["sample_metric_dev_sample_metric_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dev Token
         * @description Local-only: mint a dev JWT for exercising MULTI_TENANT=true (plan 05 §4).
         *     Creates the org, user, and membership if they don't exist, so the token is
         *     immediately usable against RLS-scoped queries.
         */
        post: operations["dev_token_dev_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentOut */
        AgentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Connector Id */
            connector_id: string | null;
            /** Status */
            status: string;
            /** Last Heartbeat At */
            last_heartbeat_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AgentRegisterIn */
        AgentRegisterIn: {
            /**
             * Connector Id
             * Format: uuid
             */
            connector_id: string;
        };
        /** AgentRegisterOut */
        AgentRegisterOut: {
            agent: components["schemas"]["AgentOut"];
            /** Ingestion Token */
            ingestion_token: string;
            /** Compose File */
            compose_file: string;
        };
        /** AnomalyOut */
        AnomalyOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Metric Id
             * Format: uuid
             */
            metric_id: string;
            /**
             * Detected At
             * Format: date-time
             */
            detected_at: string;
            /** Actual Value */
            actual_value: number;
            /** Expected Value */
            expected_value: number | null;
            /** Severity */
            severity: string;
            /** Method */
            method: string;
            /** Acknowledged At */
            acknowledged_at: string | null;
        };
        /** ConnectorCreate */
        ConnectorCreate: {
            /** Connector Definition Key */
            connector_definition_key: string;
            /** Name */
            name: string;
            /** Config */
            config?: {
                [key: string]: unknown;
            };
            /**
             * Ingestion Method
             * @default pull
             */
            ingestion_method: string;
            /** Schedule Cron */
            schedule_cron?: string | null;
            /** Secret */
            secret?: string | null;
        };
        /** ConnectorDefinitionOut */
        ConnectorDefinitionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Config Schema */
            config_schema: {
                [key: string]: unknown;
            };
            /** Supports Push */
            supports_push: boolean;
            /** Supports Pull */
            supports_pull: boolean;
            /** Supports Agent */
            supports_agent: boolean;
        };
        /** ConnectorOut */
        ConnectorOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Connector Definition Id
             * Format: uuid
             */
            connector_definition_id: string;
            /** Name */
            name: string;
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Ingestion Method */
            ingestion_method: string;
            /** Schedule Cron */
            schedule_cron: string | null;
            /** Webhook Token */
            webhook_token: string | null;
            /** Status */
            status: string;
        };
        /** ConnectorRunOut */
        ConnectorRunOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Status */
            status: string;
            /** Records Ingested */
            records_ingested: number | null;
            /** Error Message */
            error_message: string | null;
        };
        /** ConnectorUpdate */
        ConnectorUpdate: {
            /** Name */
            name?: string | null;
            /** Config */
            config?: {
                [key: string]: unknown;
            } | null;
            /** Schedule Cron */
            schedule_cron?: string | null;
            /** Status */
            status?: string | null;
        };
        /** DashboardOut */
        DashboardOut: {
            /** Connectors */
            connectors: number;
            /** Connectors Error */
            connectors_error: number;
            /** Metrics */
            metrics: number;
            /** Data Points */
            data_points: number;
            /** Points Last 24H */
            points_last_24h: number;
            /** Forecast Runs Completed */
            forecast_runs_completed: number;
            /** Agents Active */
            agents_active: number;
            /** Unread Notifications */
            unread_notifications: number;
            /** Open Anomalies */
            open_anomalies: number;
        };
        /** DataPointOut */
        DataPointOut: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Value */
            value: number;
            /** Source */
            source: string;
        };
        /** DevTokenIn */
        DevTokenIn: {
            /**
             * Org Name
             * @default Dev Org
             */
            org_name: string;
            /**
             * Email
             * @default dev@forecast.local
             */
            email: string;
            /**
             * Role
             * @default owner
             */
            role: string;
        };
        /** DevTokenOut */
        DevTokenOut: {
            /** Token */
            token: string;
            /** Org Id */
            org_id: string;
            /** User Id */
            user_id: string;
            /** Role */
            role: string;
        };
        /** EdaReportOut */
        EdaReportOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Metric Id
             * Format: uuid
             */
            metric_id: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Stationarity */
            stationarity: {
                [key: string]: unknown;
            };
            /** Seasonality */
            seasonality: {
                [key: string]: unknown;
            };
            /** Acf Pacf */
            acf_pacf: {
                [key: string]: unknown;
            };
        };
        /** ForecastCreate */
        ForecastCreate: {
            /**
             * Horizon
             * @default 24
             */
            horizon: number;
            /**
             * Model
             * @default auto
             */
            model: string;
        };
        /** ForecastPointOut */
        ForecastPointOut: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Predicted */
            predicted: number;
            /** Lower */
            lower: number | null;
            /** Upper */
            upper: number | null;
        };
        /** ForecastRunOut */
        ForecastRunOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Metric Id
             * Format: uuid
             */
            metric_id: string;
            /** Model Type */
            model_type: string;
            /** Model Params */
            model_params: {
                [key: string]: unknown;
            };
            /** Horizon */
            horizon: number;
            /** Status */
            status: string;
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Error Message */
            error_message: string | null;
            /** Warning */
            warning?: string | null;
            /**
             * Low Confidence
             * @default false
             */
            low_confidence: boolean;
            /** Backtest */
            backtest?: {
                [key: string]: unknown;
            } | null;
            /** Points */
            points?: components["schemas"]["ForecastPointOut"][];
        };
        /** ForecastRunSummaryOut */
        ForecastRunSummaryOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Metric Id
             * Format: uuid
             */
            metric_id: string;
            /** Model Type */
            model_type: string;
            /** Resolved Model */
            resolved_model: string | null;
            /** Horizon */
            horizon: number;
            /** Status */
            status: string;
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Warning */
            warning: string | null;
            /** Error Message */
            error_message: string | null;
            /**
             * Low Confidence
             * @default false
             */
            low_confidence: boolean;
            /** Cv Mase */
            cv_mase?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IngestPayload
         * @description Agent → api and webhook → api ingestion contract (doc 1 §5.3).
         */
        IngestPayload: {
            /** Metric Key */
            metric_key: string;
            /** Points */
            points: components["schemas"]["Point"][];
        };
        /** MetricCreate */
        MetricCreate: {
            /** Name */
            name: string;
            /** Key */
            key: string;
            /** Unit */
            unit?: string | null;
            /** Seasonal Period */
            seasonal_period?: number | null;
            /** Extraction Config */
            extraction_config?: {
                [key: string]: unknown;
            };
        };
        /** MetricDataOut */
        MetricDataOut: {
            /**
             * Metric Id
             * Format: uuid
             */
            metric_id: string;
            /** Points */
            points: components["schemas"]["DataPointOut"][];
        };
        /**
         * MetricListItemOut
         * @description Dataset-list shape (doc 4 §3): sparkline + freshness at a glance.
         */
        MetricListItemOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Connector Id
             * Format: uuid
             */
            connector_id: string;
            /** Name */
            name: string;
            /** Key */
            key: string;
            /** Unit */
            unit: string | null;
            /** Seasonal Period */
            seasonal_period: number | null;
            /** Connector Name */
            connector_name: string;
            /** N Points */
            n_points: number;
            /** Last Updated */
            last_updated: string | null;
            /** Spark */
            spark: number[];
        };
        /** MetricOut */
        MetricOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Connector Id
             * Format: uuid
             */
            connector_id: string;
            /** Name */
            name: string;
            /** Key */
            key: string;
            /** Unit */
            unit: string | null;
            /** Seasonal Period */
            seasonal_period: number | null;
        };
        /** MetricUpdate */
        MetricUpdate: {
            /** Name */
            name?: string | null;
            /** Unit */
            unit?: string | null;
            /** Seasonal Period */
            seasonal_period?: number | null;
        };
        /** NotificationOut */
        NotificationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Type */
            type: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Read At */
            read_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * Point
         * @description One observation of a series (doc 1 §4.1, doc 3 §2).
         */
        Point: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Value */
            value: number;
        };
        /** SampleMetricOut */
        SampleMetricOut: {
            /** Value */
            value: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_definitions_connector_definitions_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorDefinitionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_connectors_connectors_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_connector_connectors_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectorCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_connector_connectors__connector_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                connector_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_connector_connectors__connector_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                connector_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_connector_connectors__connector_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                connector_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectorUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_connector_runs_connectors__connector_id__runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                connector_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_metrics_connectors__connector_id__metrics_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                connector_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_metric_connectors__connector_id__metrics_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                connector_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MetricCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricListItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metric_metrics__metric_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                metric_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_metric_metrics__metric_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                metric_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_metric_metrics__metric_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                metric_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MetricUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_metric_forecasts_metrics__metric_id__forecasts_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                metric_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastRunSummaryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_metric_anomalies_metrics__metric_id__anomalies_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                metric_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnomalyOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metric_data_metrics__metric_id__data_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                metric_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricDataOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enqueue_forecast_metrics__metric_id__forecast_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                metric_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForecastCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_forecast_forecasts__forecast_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                forecast_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_forecast_forecasts__forecast_id__export_get: {
        parameters: {
            query?: {
                format?: string;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                forecast_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    share_forecast_forecasts__forecast_id__share_post: {
        parameters: {
            query?: {
                format?: string;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                forecast_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_shared_export_exports__share_token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                share_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    webhook_ingress_webhooks__webhook_token__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agent_ingest_ingest_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agent_heartbeat_agents_heartbeat_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_agents_agents_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_agent_agents_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentRegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRegisterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_agent_agents__agent_id__revoke_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_eda_metrics__metric_id__eda_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                metric_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdaReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_eda_metrics__metric_id__eda_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                metric_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdaReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notifications_notifications_get: {
        parameters: {
            query?: {
                unread_only?: boolean;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_read_notifications__notification_id__read_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                notification_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_all_read_notifications_read_all_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unread_count_notifications_unread_count_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_dashboard_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sample_metric_dev_sample_metric_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleMetricOut"];
                };
            };
        };
    };
    dev_token_dev_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevTokenIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevTokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
